name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Install ChromeDriver
        run: |
            CHROME_VERSION=$(google-chrome --version | grep -oP 'Google Chrome \K([\d\.]+)') \
            && echo $CHROME_VERSION \
            && DOWNLOAD_URL="https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chromedriver-linux64.zip" \
            && echo "$DOWNLOAD_URL" \
            && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver-linux64.zip $DOWNLOAD_URL \
            && cd /tmp \
            && unzip chromedriver-linux64.zip \
            && rm -rf chromedriver-linux64.zip \
            && sudo mv chromedriver /usr/local/bin/chromedriver \
            && sudo chmod +x /usr/local/bin/chromedriver \
            && chromedriver --version
